version: "3.9"

services:
  app:
    container_name: demo_app
    image: "streamlit:${TAG}"
    build:
      dockerfile: ./program/Dockerfile
      context: .
      cache_from:
        - "streamlit:${TAG}"
    ports:
      - 8501:8501
      # - 5000:5000 # Mlfow port
    # volumes:
    #   - ./:/app

  documenter:
    container_name: documentor
    build:
      dockerfile: ./library/docs/Dockerfile
      args:
        - AUTHOR_NAME=JHF
        - VERSION=0.4
        - CODEBASE_NAME=nnfs

    # tty: true
    # stdin_open: true

    volumes:
      - ./library/docs/documents:/library/docs/documents
    # TODO: Add a container just for running tests

  # tests:
  #   container_name: tester
  #   build:

  #   tty: true
  #   stdin_open: true

volumes:
  documents: