version: "3.9"

services:
  app:
    container_name: demo_app
    image: "streamlit:${TAG}"
    build:
      context: .
      dockerfile: ./program/Dockerfile
      cache_from:
        - "streamlit:${TAG}"
    ports:
      - 8501:8501
      # - 5000:5000 # Mlfow port
    # volumes:
    #   - ./:/app
    tty: true
    stdin_open: true

volumes:
  documents:
