version: "3.9"
services:
  app:
    container_name: streamlit-app
    image: "streamlit:${TAG}"
    build:
      dockerfile: ./Dockerfile
      context: .
      cache_from:
        - "streamlit:${TAG}"
    ports:
      - 8501:8501
    # volumes:
    #   - ./:/app 
