version: "3.9"

services:
  app:
    container_name: demo_app
    build:
      context: .
      dockerfile: ./program/Dockerfile
    ports:
      - 8501:8501
    # volumes:
    #   - ./:/app
    # tty: true
    # stdin_open: true
