name: Library Builder

# triggers for our workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose
        working-directory: .

      - name: Run Tests
        run: docker compose up -d --build
        working-directory: .
